linux_build_and_test:
  script:
    - pip install tox
    - tox
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  image: python:3.8.8
  tags:
    - docker

pages:
  script:
    - pip install -r docs/requirements.txt
    - sphinx-build -b html docs/source public
  image: python:3.8.8
  artifacts:
    paths:
    - public
  only:
    - main
