linux_build_and_test:
  cache:
    paths:
      - requirements-dev.txt
    when: 'on_success'
    key: 'build_and_test'
  script:
    - pip install tox
    - tox
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  image: python:3.8.8
  tags:
    - docker

deploy_cloud_functions:
  image: google/cloud-sdk:latest
  only:
    - feature/send-cleaned-data-to-bigquery
  dependencies:
    - linux_build_and_test
  script:
    # Authenticate using the service account stored here: https://gitlab.com/groups/{YOUR_GITLAB_PROJECT}/-/settings/ci_cd
    - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS --project aerosense-twined
    - gcloud iam service-accounts add-iam-policy-binding create-gateway-installation@aerosense-twined.iam.gserviceaccount.com --member=$MEMBER --role=roles/iam.serviceAccountUser

    # Deploy
    - gcloud functions deploy create-installation --source cloud_function --entry-point create_installation --runtime python39 --trigger-http --security-level secure-always --region europe-west6 --set-env-vars DESTINATION_PROJECT_NAME=aerosense-twined,BIG_QUERY_DATASET_NAME=greta

pages:
  cache:
    paths:
      - docs/requirements.txt
    when: 'on_success'
    key: 'pages'
  script:
    - pip install -r docs/requirements.txt
    - sphinx-build -b html docs/source public
  image: python:3.8.8
  artifacts:
    paths:
    - public
  only:
    - main
