linux_build_and_test:
  cache:
    paths:
      - requirements-dev.txt
    when: 'on_success'
    key: 'build_and_test'
  script:
    - pip install tox
    - tox
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  image: python:3.8.8
  tags:
    - docker

tag:
  only:
    - main
  script:
    - git tag -a $(python setup.py --version)
    - git push origin --tags
  image: python:3.8.8

pages:
  cache:
    paths:
      - docs/requirements.txt
    when: 'on_success'
    key: 'pages'
  script:
    - pip install -r docs/requirements.txt
    - sphinx-build -b html docs/source public
  image: python:3.8.8
  artifacts:
    paths:
    - public
  only:
    - main
