default:
  image: python:3.8.8

build_and_test:
  cache:
    paths:
      - requirements-dev.txt
    when: 'on_success'
    key: 'build_and_test'
  script:
    - python3 -m venv test-venv
    - bash test-venv/bin/activate
    - pip install -r requirements-dev.txt
    - coverage run -m unittest
    - coverage report
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'

pages:
  cache:
    paths:
      - docs/requirements.txt
    when: 'on_success'
    key: 'pages'
  script:
  - python3 -m venv docs-venv
  - bash docs-venv/bin/activate
  - pip install -r docs/requirements.txt
  - sphinx-build -b html docs/source public
  artifacts:
    paths:
    - public
  only:
    - master
