name: gcloud-deploy

on:
  push:
    branches:
      - main
      - test

jobs:
  get-prefix:
    runs-on: ubuntu-latest
    outputs:
      name_prefix: ${{ steps.prefix.outputs.name_prefix }}
      dataset_name_prefix: ${{ steps.prefix.outputs.dataset_name_prefix }}
    steps:
      - name: Get prefix (test- or nothing for production)
        id: prefix
        run: |
          echo ${{ github.ref }}
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "::set-output name=name_prefix::"
            echo "::set-output name=dataset_name_prefix::"
          else
            echo "::set-output name=name_prefix::test-"
            echo "::set-output name=dataset_name_prefix::test_"
          fi

  deploy-add-sensor-type:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    needs: get-prefix
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/885434704038/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "data-gateway-ci-testing@aerosense-twined.iam.gserviceaccount.com"

      - uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ needs.get-prefix.outputs.name_prefix }}add-sensor-type
          description: Allows addition of a new sensor type whose values will be accepted into the database
          entry_point: add_sensor_type
          runtime: python39
          region: europe-west6
          env_vars: BIG_QUERY_DATASET_NAME=${{ needs.get-prefix.outputs.dataset_name_prefix }}greta,COMPUTE_PROVIDER=GOOGLE_CLOUD_FUNCTION,DESTINATION_PROJECT_NAME=aerosense-twined
          source_dir: cloud_functions

  deploy-create-installation:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    needs: get-prefix
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/885434704038/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "data-gateway-ci-testing@aerosense-twined.iam.gserviceaccount.com"

      - uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ needs.get-prefix.outputs.name_prefix }}create-installation
          description: Allows creation of a new installation
          entry_point: create_installation
          runtime: python39
          region: europe-west6
          env_vars: BIG_QUERY_DATASET_NAME=${{ needs.get-prefix.outputs.dataset_name_prefix }}greta,COMPUTE_PROVIDER=GOOGLE_CLOUD_FUNCTION,DESTINATION_PROJECT_NAME=aerosense-twined
          source_dir: cloud_functions

  deploy-ingress-eu:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    needs: get-prefix
    steps:
      - id: checkout
        uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/885434704038/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider"
          service_account: "data-gateway-ci-testing@aerosense-twined.iam.gserviceaccount.com"

      - uses: google-github-actions/deploy-cloud-functions@v0
        with:
          name: ${{ needs.get-prefix.outputs.name_prefix }}ingress-eu
          entry_point: upload_window
          runtime: python39
          region: europe-west6
          memory_mb: 1024
          env_vars: BIG_QUERY_DATASET_NAME=${{ needs.get-prefix.outputs.dataset_name_prefix }}greta,COMPUTE_PROVIDER=GOOGLE_CLOUD_FUNCTION,DESTINATION_PROJECT_NAME=aerosense-twined,DESTINATION_BUCKET_NAME=data-gateway-processed-data,SOURCE_PROJECT_NAME=aerosense-twined
          source_dir: cloud_functions
          event_trigger_type: google.storage.object.finalize
          event_trigger_resource: projects/_/buckets/${{ needs.get-prefix.outputs.name_prefix }}aerosense-ingress-eu
          event_trigger_service: storage.googleapis.com
